### ISSUE TITLE
testing with jest

### ISSUE THREAD

**Issue by vladimir-ivanov** [facebookincubator/redux-react-hook#56]
Are there any plans to provide mocks for the store/ dispatch functions please? 
Can not find any examples of how to test components which connect to the store via redux-react-hooks

Thanks

**Comment by ianobermiller** [comment]
We probably won't provide any mocks with the library. My preference is to add an actual provider and use the real store (or a mock store) but with all real `redux-react-hook`. An alternative is to use [Jest to mock out the module](https://jestjs.io/docs/en/jest-object.html#jestmockmodulename-factory-options) itself, which isn't too bad because `mapState` returns the data you're looking for and `dispatch` returns a function.

Something like this, if you use `create`:

```tsx
jest.mock('redux-react-hook', () => {
  return {
    create() {
      return {dispatch: jest.fn(), mapState: jest.fn()};
    }
  };
});
```

**Comment by rob-gordon** [comment]
> My preference is to add an actual provider and use the real store (or a mock store) but with all real redux-react-hook

Do you have an example of this anywhere?

**Comment by ianobermiller** [comment]
For an example of testing with a real store, see the tests for `redux-react-hook` itself: https://github.com/facebookincubator/redux-react-hook/blob/master/src/__tests__/index-test.tsx
